export interface Product {
  id: string
  name: string
  price: number
  discountPrice?: number
  discountPercent?: number
  ratingValue: number
  ratingCount: number
  isHot: boolean
  colors: string[]
  category: string
  imageUrl: string
}

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Nike Air Max 270 React",
    price: 299.43,
    discountPrice: 199.43,
    discountPercent: 33,
    ratingValue: 4.5,
    ratingCount: 145,
    isHot: true,
    colors: ["#000000", "#ffffff", "#3b82f6"],
    category: "Nike",
    imageUrl: "/nike-air-max-270-react-sneakers.jpg",
  },
  {
    id: "2",
    name: "Nike Air Max 270 React",
    price: 299.43,
    discountPrice: 199.43,
    discountPercent: 33,
    ratingValue: 4.2,
    ratingCount: 98,
    isHot: true,
    colors: ["#dc2626", "#000000"],
    category: "Nike",
    imageUrl: "/nike-air-max-red-sneakers.jpg",
  },
  {
    id: "3",
    name: "Nike Air Max 270 React",
    price: 299.43,
    discountPrice: 199.43,
    discountPercent: 33,
    ratingValue: 4.8,
    ratingCount: 203,
    isHot: true,
    colors: ["#f59e0b", "#000000"],
    category: "Nike",
    imageUrl: "/nike-air-max-beige-sneakers.jpg",
  },
  {
    id: "4",
    name: "Nike Air Max 270 React",
    price: 299.43,
    discountPrice: 199.43,
    discountPercent: 33,
    ratingValue: 4.3,
    ratingCount: 156,
    isHot: true,
    colors: ["#3b82f6", "#ffffff"],
    category: "Nike",
    imageUrl: "/nike-air-max-blue-white-sneakers.jpg",
  },
  {
    id: "5",
    name: "Nike Air Max 270 React",
    price: 299.43,
    discountPrice: 199.43,
    discountPercent: 33,
    ratingValue: 4.6,
    ratingCount: 187,
    isHot: true,
    colors: ["#f59e0b", "#dc2626"],
    category: "Nike",
    imageUrl: "/nike-air-max-yellow-red-sneakers.jpg",
  },
  {
    id: "6",
    name: "Nike Air Force 1",
    price: 90.0,
    ratingValue: 4.4,
    ratingCount: 445,
    isHot: false,
    colors: ["#ffffff", "#000000"],
    category: "Nike",
    imageUrl: "/nike-air-force-1-white-sneakers.jpg",
  },
  // Add more products to reach 24+ items
  {
    id: "7",
    name: "Adidas Ultraboost 22",
    price: 180.0,
    ratingValue: 4.7,
    ratingCount: 89,
    isHot: false,
    colors: ["#000000", "#ffffff"],
    category: "Adidas",
    imageUrl: "/adidas-ultraboost-black-white-sneakers.jpg",
  },
  {
    id: "8",
    name: "Adidas Stan Smith",
    price: 85.0,
    ratingValue: 4.5,
    ratingCount: 234,
    isHot: false,
    colors: ["#ffffff", "#10b981"],
    category: "Adidas",
    imageUrl: "/adidas-stan-smith-white-green-sneakers.jpg",
  },
  {
    id: "9",
    name: "Vans Old Skool",
    price: 65.0,
    ratingValue: 4.3,
    ratingCount: 167,
    isHot: false,
    colors: ["#000000", "#ffffff"],
    category: "Vans",
    imageUrl: "/vans-old-skool-black-white-sneakers.jpg",
  },
  {
    id: "10",
    name: "Converse Chuck Taylor",
    price: 55.0,
    ratingValue: 4.2,
    ratingCount: 298,
    isHot: false,
    colors: ["#dc2626", "#000000", "#ffffff"],
    category: "All Stars",
    imageUrl: "/converse-chuck-taylor-red-sneakers.jpg",
  },
  {
    id: "11",
    name: "Nike Air Force 1",
    price: 90.0,
    ratingValue: 4.6,
    ratingCount: 445,
    isHot: false,
    colors: ["#ffffff", "#000000"],
    category: "Nike",
    imageUrl: "/nike-air-force-1-white-sneakers.jpg",
  },
  {
    id: "12",
    name: "Adidas Gazelle",
    price: 80.0,
    ratingValue: 4.4,
    ratingCount: 156,
    isHot: false,
    colors: ["#3b82f6", "#dc2626"],
    category: "Adidas",
    imageUrl: "/adidas-gazelle-blue-sneakers.jpg",
  },
  {
    id: "13",
    name: "Vans Authentic",
    price: 50.0,
    ratingValue: 4.1,
    ratingCount: 89,
    isHot: false,
    colors: ["#000000", "#dc2626"],
    category: "Vans",
    imageUrl: "/vans-authentic-black-sneakers.jpg",
  },
  {
    id: "14",
    name: "Nike React Element",
    price: 130.0,
    ratingValue: 4.5,
    ratingCount: 123,
    isHot: false,
    colors: ["#f59e0b", "#000000"],
    category: "Nike",
    imageUrl: "/nike-react-element-yellow-sneakers.jpg",
  },
  {
    id: "15",
    name: "Adidas NMD R1",
    price: 140.0,
    ratingValue: 4.3,
    ratingCount: 178,
    isHot: false,
    colors: ["#000000", "#3b82f6"],
    category: "Adidas",
    imageUrl: "/adidas-nmd-r1-black-blue-sneakers.jpg",
  },
  {
    id: "16",
    name: "Converse One Star",
    price: 70.0,
    ratingValue: 4.0,
    ratingCount: 67,
    isHot: false,
    colors: ["#ffffff", "#f59e0b"],
    category: "All Stars",
    imageUrl: "/converse-one-star-white-sneakers.jpg",
  },
  {
    id: "17",
    name: "Nike Blazer Mid",
    price: 100.0,
    ratingValue: 4.4,
    ratingCount: 234,
    isHot: false,
    colors: ["#ffffff", "#dc2626"],
    category: "Nike",
    imageUrl: "/nike-blazer-mid-white-red-sneakers.jpg",
  },
  {
    id: "18",
    name: "Vans Slip-On",
    price: 55.0,
    ratingValue: 4.2,
    ratingCount: 145,
    isHot: false,
    colors: ["#000000", "#ffffff"],
    category: "Vans",
    imageUrl: "/vans-slip-on-black-white-sneakers.jpg",
  },
  {
    id: "19",
    name: "Adidas Superstar",
    price: 85.0,
    ratingValue: 4.6,
    ratingCount: 356,
    isHot: false,
    colors: ["#ffffff", "#000000"],
    category: "Adidas",
    imageUrl: "/adidas-superstar-white-black-sneakers.jpg",
  },
  {
    id: "20",
    name: "Nike Dunk Low",
    price: 110.0,
    ratingValue: 4.7,
    ratingCount: 289,
    isHot: false,
    colors: ["#3b82f6", "#ffffff"],
    category: "Nike",
    imageUrl: "/nike-dunk-low-blue-white-sneakers.jpg",
  },
  {
    id: "21",
    name: "Converse Platform",
    price: 75.0,
    ratingValue: 4.3,
    ratingCount: 112,
    isHot: false,
    colors: ["#000000", "#dc2626"],
    category: "All Stars",
    imageUrl: "/converse-platform-black-sneakers.jpg",
  },
  {
    id: "22",
    name: "Vans Era",
    price: 60.0,
    ratingValue: 4.1,
    ratingCount: 78,
    isHot: false,
    colors: ["#f59e0b", "#000000"],
    category: "Vans",
    imageUrl: "/vans-era-yellow-black-sneakers.jpg",
  },
  {
    id: "23",
    name: "Nike Air Max 90",
    price: 120.0,
    ratingValue: 4.5,
    ratingCount: 198,
    isHot: false,
    colors: ["#ffffff", "#3b82f6"],
    category: "Nike",
    imageUrl: "/nike-air-max-90-white-blue-sneakers.jpg",
  },
  {
    id: "24",
    name: "Adidas Forum Low",
    price: 90.0,
    ratingValue: 4.2,
    ratingCount: 134,
    isHot: false,
    colors: ["#ffffff", "#dc2626"],
    category: "Adidas",
    imageUrl: "/adidas-forum-low-white-red-sneakers.jpg",
  },
  {
    id: "25",
    name: "Puma RS-X",
    price: 150.0,
    ratingValue: 4.3,
    ratingCount: 120,
    isHot: false,
    colors: ["#000000", "#ffffff"],
    category: "Puma",
    imageUrl: "/puma-rs-x-black-white-sneakers.jpg",
  },
  {
    id: "26",
    name: "New Balance 574",
    price: 160.0,
    ratingValue: 4.4,
    ratingCount: 130,
    isHot: false,
    colors: ["#3b82f6", "#dc2626"],
    category: "New Balance",
    imageUrl: "/new-balance-574-blue-red-sneakers.jpg",
  },
  {
    id: "27",
    name: "Reebok Classic",
    price: 80.0,
    ratingValue: 4.2,
    ratingCount: 140,
    isHot: false,
    colors: ["#ffffff", "#000000"],
    category: "Reebok",
    imageUrl: "/reebok-classic-white-sneakers.jpg",
  },
  {
    id: "28",
    name: "Under Armour Curry 8",
    price: 170.0,
    ratingValue: 4.5,
    ratingCount: 150,
    isHot: false,
    colors: ["#f59e0b", "#000000"],
    category: "Under Armour",
    imageUrl: "/under-armour-curry-8-yellow-sneakers.jpg",
  },
  {
    id: "29",
    name: "Jordan Air 1",
    price: 250.0,
    ratingValue: 4.7,
    ratingCount: 160,
    isHot: false,
    colors: ["#000000", "#ffffff"],
    category: "Jordan",
    imageUrl: "/jordan-air-1-black-white-sneakers.jpg",
  },
  {
    id: "30",
    name: "Converse Checkerboard",
    price: 60.0,
    ratingValue: 4.1,
    ratingCount: 170,
    isHot: false,
    colors: ["#ffffff", "#000000"],
    category: "Converse",
    imageUrl: "/converse-checkerboard-sneakers.jpg",
  },
]

export const categories = ["Nike", "Adidas", "Vans", "All Stars", "Puma", "New Balance", "Reebok", "Under Armour"]

export const colors = ["#000000", "#ffffff", "#3b82f6", "#dc2626", "#f59e0b", "#10b981", "#8b5cf6", "#ec4899"]

export const brands = [
  "Nike",
  "Adidas",
  "Vans",
  "All Stars",
  "Puma",
  "New Balance",
  "Reebok",
  "Under Armour",
  "Jordan",
  "Converse",
]
